# server {
#     listen 80;

#     location / {
#         proxy_pass http://fastapi:8000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }

server {
    listen 80;

    # Client site → http://IP/
    location / {
        root /usr/share/nginx/html/client;
        index index.html;
        try_files /client$uri /client/index.html;
    }

    # Staff site → http://IP/staff
    location /staff/ {
        root /usr/share/nginx/html;
        try_files /staff$uri /staff/index.html;
    }

    # API → http://IP/api/...
    location /api/ {
        proxy_pass http://fastapi:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}